import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Mahmoud Elrashedy</title>
        <meta name="Description" content="FrontEnd Developer, 
        Building Responsive Websites with the latest Technologies" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
